### ISSUE TITLE
Asynchronous Actions

### ISSUE THREAD

**Issue by busypeoples** [RoyalIcing/react-organism#14]
Is it possible to declare or compose asynchronous actions with setState functions? 
For example something like `run`: 
```js
run(doAsyncFetch, (valueFromAsyncFetch) => ({ foo }) => { foo: foo + valueFromAsyncFetch})
```
I think this would be very beneficial. Also, what is `load`? Can't find any information on this. Seems it is able to take care of effects.
Also what if one would like to use `Tasks` instead of `Promises` how can this be defined in user land.
These are the last open questions. 
Great library!

**Comment by BurntCaramel** [comment]
Yes, a Promise may resolve to an updater function, like so:
```js
doAsyncFetch
  .then((valueFromAsyncFetch) => ({ foo }) => ({ foo: foo + valueFromAsyncFetch}))
```

What do you mean by Tasks instead of Promises? What do they do differently? Promise is great because it’s part of the ES spec. Thanks!

**Comment by busypeoples** [comment]
Should definitely support `Promises`. Just meant what if somebody uses `Tasks`, it should be able to do. The main difference is that Tasks are lazy and you `fork`, then they start to run. See also https://glebbahmutov.com/blog/difference-between-promise-and-task/

But looking at your `doAsyncFetch` example, it might even work out of the box. 
```js
Task(foo).fork(() => ({}), (valueFromAsyncFetch) => ({ foo }) => ({ foo: foo + valueFromAsyncFetch}))
```

**Comment by BurntCaramel** [comment]
OK, yeah so technically react-organism will accept any thenable (anything having a `.then` method) — possibly there are enhancers or options for `Task` that add this? As that would open up interoperability with a lot of libraries then. I will see what the further demand is for `Task`s before adding in support.

**Comment by BurntCaramel** [comment]
- http://folktale.origamitower.com/api/v2.0.0/en/folktale.concurrency.task.html#running-tasks
- http://folktale.origamitower.com/docs/v2.0.0/migrating/from-data.task/#memoise

It looks as though a running task supports converting into a Promise using the `.promise()` method.
