### ISSUE TITLE
Immutable data and deep state change.

### ISSUE THREAD

**Issue by ismail-codar** [RoyalIcing/react-organism#21]
Hi @BurntCaramel. I tried this project a little bit. I could not get along with https://github.com/kolodny/immutability-helper or https://github.com/engineforce/ImmutableAssign

Your examples are generally based basic state values. Like counter: `({ count: 0 })`. Multi state approach is not efficient according to me.

I think this project may be work with complex nested state values. For example:

state: `{my:{counter:{count:0}}}`
updateCountHandler: `
(props) => {
const newProps = deepCopy(props);
newProps.my.counter.count = newProps.my.counter.count+1;
return newProps
}
`

**Comment by BurntCaramel** [comment]
Hi @ismail-codar sorry for not replying.

Yes this is a common drawback of immutable data, you’ll find it in other libraries that use it such as Redux. There are some libraries such as [immer](https://github.com/mweststrate/immer) which allow you to change immutable data feel with familiar mutable methods.
